name: Build WechatBypass

on:
  push:
    branches: [wechat-bypass, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Theos
        run: |
          rm -rf theos
          git clone --recursive https://github.com/theos/theos.git theos
          export THEOS=${{ github.workspace }}/theos
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Prepare iOS SDK
        run: |
          export THEOS=${{ github.workspace }}/theos
          rm -rf $THEOS/sdks
          mkdir -p $THEOS/sdks
          git clone --depth 1 --filter=blob:none --sparse https://github.com/theos/sdks.git $THEOS/sdks-temp
          cd $THEOS/sdks-temp
          git sparse-checkout set iPhoneOS14.5.sdk
          mv iPhoneOS14.5.sdk $THEOS/sdks/
          cd ..
          rm -rf $THEOS/sdks-temp

      - name: Install dependencies
        run: |
          brew install make xz ldid dpkg

      - name: Build rootful package
        run: |
          export THEOS=${{ github.workspace }}/theos
          rm -rf .theos packages
          gmake clean package FINALPACKAGE=1

      - name: Upload rootful package
        uses: actions/upload-artifact@v4
        with:
          name: "WechatBypass-rootful"
          path: ${{ github.workspace }}/packages/*.deb

      - name: Build rootless package
        run: |
          export THEOS=${{ github.workspace }}/theos
          rm -rf .theos packages
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload rootless package
        uses: actions/upload-artifact@v4
        with:
          name: "WechatBypass-rootless"
          path: ${{ github.workspace }}/packages/*.deb
